# Generated by Django 3.1.2 on 2020-11-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_choice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(default='utilisateur', max_length=25)),
                ('is_admin', models.BooleanField(default=False)),
                ('favorites', models.ManyToManyField(related_name='favoris', to='food_choice.Favoris')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
