# Generated by Django 3.1.2 on 2020-11-10 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, null=True)),
                ('code', models.CharField(default='0000000000000', max_length=13)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('photo_url', models.TextField(null=True)),
                ('product_url', models.TextField(null=True)),
                ('nutrition_grade', models.CharField(max_length=1, null=True)),
                ('energy_100g', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('saturates', models.IntegerField(default=0)),
                ('carbohydrate', models.IntegerField(default=0)),
                ('sugars', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('fiber', models.IntegerField(default=0)),
                ('salt', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='product', to='food_choice.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='food_choice.product')),
                ('product_substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='food_choice.product')),
            ],
        ),
    ]
