# Generated by Django 3.1.2 on 2020-11-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=150)),
                ('code', models.PositiveBigIntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('photo_uri', models.TextField(blank=True)),
                ('product_uri', models.TextField(blank=True)),
                ('nutrition_grade', models.CharField(max_length=1)),
                ('energy_100g', models.PositiveSmallIntegerField(default=0)),
                ('fat', models.PositiveSmallIntegerField(default=0)),
                ('saturates', models.PositiveSmallIntegerField(default=0)),
                ('carbohydrate', models.PositiveSmallIntegerField(default=0)),
                ('sugars', models.PositiveSmallIntegerField(default=0)),
                ('protein', models.PositiveSmallIntegerField(default=0)),
                ('fiber', models.PositiveSmallIntegerField(default=0)),
                ('salt', models.PositiveSmallIntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='product', to='food_choice.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='food_choice.product')),
                ('product_substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='food_choice.product')),
            ],
        ),
    ]
